version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      - mysql
     
  frontend:
    build: ./frontend
    ports: 
      - "4200:4200"
    container_name: angular_container
    
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: asiste-db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    container_name: database_container
    volumes:
      - ./data/mysql:/var/lib/mysql
