version: "3.9"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asiste
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports: 
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mysql_data:

