version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: database_container
    environment:
      MYSQL_DATABASE: asiste-db
      MYSQL_ALLOW-EMPTY-PASSWORD: "yes"
    ports: 
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      - db 
    links:
      - db
  frontend:
    build: ./frontend
    ports: 
      - "4200:4200"
    container_name: angular_container 
