version: "3.9"
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
 
  frontend:
    build: ./frontend
    ports: 
      - "4200:4200"
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password'
      MYSQL_DATABASE: asiste_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
