version: "3.9"
services:
  db:
    image: mysql:latest
    # container_name: database_container
    volumes:
      - ./data:/var/lib/mysql
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "asiste"
    expose:
      - "3306"
    
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000 
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - frontend
  frontend:
    command: ng serve --port 4300 --host 0.0.0.0
    build: ./frontend
    ports: 
      - "4300:4300"
